# Don't Remove Credit Tg - @MR_ABHAY_K
# Ask Doubt on telegram @AK_BOTZ_SUPPORT

services:
  - type: web
    name: your-app-name
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 main.py"
    envVars:
      - key: API_ID
        value: YOUR_API_ID
      - key: API_HASH
        value: YOUR_API_HASH
      - key: BOT_TOKEN
        value: YOUR_BOT_TOKEN


# Don't Remove Credit Tg - @MR_ABHAY_K
# Ask Doubt on telegram @AK_BOTZ_SUPPORT

        
